version: '3'

services:
  database:
    image: mysql:5.6
    container_name: estoque-db
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=estoque_laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: estoque-phpmyadmin
    depends_on:
      - database
    links:
      - database
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1

volumes:
  data: